### ISSUE TITLE
Setext Headlines with 4 spaces in front still get partly highlighted

### ISSUE THREAD

**Issue by Waqar144** [pbek/qmarkdowntextedit#101]
Example:
```
.... Headline
======
```

`====` still gets highlighted as headline

**Comment by pbek** [comment]
```
    headline
===========
```

(4 spaces in front) still produces

![image](https://user-images.githubusercontent.com/1798101/73915135-fa610280-48ba-11ea-9202-1da599237b0f.png)

**Comment by Waqar144** [comment]
Yes, I think so.

There's a minor difference in the implementation of `highlightBlock` there.

**Comment by pbek** [comment]
Do you care to integrate it into QON? :smile:

**Comment by Waqar144** [comment]
Sure lol

**Comment by Waqar144** [comment]
> ```
>     headline
> ===========
> ```
> 
> (4 spaces in front) still produces
>  
> in QOwnNotes. Does this need more integration?

I just tried it in QON, can't reproduce it. How did you enter the headline?

**Comment by pbek** [comment]
Doesn't matter. I can paste it. I can type it. I can add spaces in the end. No highlighting unless there are only 3 or less spaces. Or was that the thing you implemented. That there is NO highlighting if there are 4 or more spaces?

What happens for you? Is my example highlighted as headline for you?

**Comment by Waqar144** [comment]
Yes, exactly. Only 3 spaces allowed😁

With 4 spaces it becomes indented code block.

The bug was that only the current block became 'indented code', while the previous/next block remained as heading which gave a very weird look.

**Comment by Waqar144** [comment]
Your example gets highlighted as
- first block = indented code
- second = No state

**Comment by pbek** [comment]
Then it's perfect. :grin:

**Comment by Waqar144** [comment]
Let's close this then✔️

**Comment by pbek** [comment]
Ah, it was an issue. :grin:
