### ISSUE TITLE
Character auto-removal for same char types doesn't work correctly

### ISSUE THREAD

**Issue by Waqar144** [pbek/qmarkdowntextedit#105]
Characters such as:
 ```
* ` _ " '
```
don't get auto removed correctly sometimes on pressing backspace.

To fix this we need to determine whether the character being removed is an 'opening' or 'closing' character.

- [x] Fix single quotes removal
- [x] Fix double quotes removal
- [x] Fix asterisk removal
- [x] Fix backtick removal
- [ ] Fix underscore removal

**Note:** Looking backward for these characters is temporarily removed until proper solution is implemented.

**Note:** Commonmark rules for some characters might not completely apply because we are removing only one character at a time. Consider `**bold**`, we need to handle this in a way that removal of first asterisk results in the removal of third asterisk.

**Comment by Waqar144** [comment]
This is fixed with https://github.com/pbek/qmarkdowntextedit/commit/af48921ee713cf93d8c83df1993fb40f90384e93 so I think its okay to close this for now

**Comment by pbek** [comment]
Fine with me. 😁
