### ISSUE TITLE
Use Qmarkdowntextedit just to view the markdown

### ISSUE THREAD

**Issue by keshavbhatt** [pbek/qmarkdowntextedit#127]
Hi, I have used QmarkDownTextEdit in one of my utility, am wondering if this can be used just to show the parsed output in QTextBrowser, etc. 
Right now it is showing output with markdown syntax in place.

**Comment by pbek** [comment]
What do you mean by "parsed output in QTextBrowser"? Can you please make an example of what you want to achieve?

**Comment by keshavbhatt** [comment]
I have attached a screenshot of one of your application QOwnNotes.
![this](https://user-images.githubusercontent.com/5965031/94411793-99ae6f00-0196-11eb-8901-5a66cc50bcdc.png)

**Comment by pbek** [comment]
No, this library doesn't do the markdown to html conversion, if that's what you were talking about.
You want to take a look at https://github.com/qownnotes/md4c/ for this.

**Comment by keshavbhatt** [comment]
Thanks, i will have a look at it.

**Comment by engineer1109** [comment]
Well done. Really need.
