### ISSUE TITLE
Highlighting support for numbered list checkboxes

### ISSUE THREAD

**Issue by pbek** [pbek/qmarkdowntextedit#134]
@Waqar144, do you think you can add highlighting support for numbered list checkboxes like `1. [ ]` or `25. [x]` too in `MarkdownHighlighter::highlightLists`?

**Comment by pbek** [comment]
md4c and Nextcloud Notes are also supporting those...

**Comment by pbek** [comment]
And the checkbox toggle from https://github.com/pbek/QOwnNotes/issues/2048 now supports it too. 😉

**Comment by Waqar144** [comment]
Yeah. Sure. If it's being supported by md4c then we should do it too

**Comment by pbek** [comment]
Awesome! 😀
