### ISSUE TITLE
Build fails with -DQT_NO_CAST_FROM_ASCII

### ISSUE THREAD

**Issue by software-made-easy** [pbek/qmarkdowntextedit#170]
When `-DQT_NO_CAST_FROM_ASCII` is defined, you cant call `QChar(' ')`(char) and `QString("String")`(const char*).
To avoid the QChar error we could use `QChar(u' ')` but this requires Qt >= 5.10.  
For QString we could use `QStringLiteral`.  

I created a issue because i don't want to create a pull request that requires Qt 5.10 without having your OK.

**Comment by pbek** [comment]
Qt 5.5+ must be supported. So best use some `#if (QT_VERSION >= QT_VERSION_CHECK(5, 10, 0))` directives.
@Waqar144, any objections?

**Comment by Waqar144** [comment]
just `QLatin1Char(...)` should be enough for us I think.

**Comment by software-made-easy** [comment]
`QLatin1Char` doesn't work everywhere(for example [here](https://github.com/pbek/qmarkdowntextedit/blob/develop/qmarkdowntextedit.h#L101))
