### ISSUE TITLE
Highlight line break

### ISSUE THREAD

**Issue by tim-gromeyer** [pbek/qmarkdowntextedit#176]
Here an image:
![Example](https://user-images.githubusercontent.com/58736434/204003686-34d627d6-62d9-4646-aa06-f50ce15e7b3a.png)

On the left side is qmarkdowntextedit, on the right side the default editor of Linux mint(xed).

**Comment by pbek** [comment]
I can feel no special urge to see that in a Markdown editor... What's the use-case?

**Comment by tim-gromeyer** [comment]
Just to make line breaks visible.

**Comment by tim-gromeyer** [comment]
Since this will not be implemented, I close the issue
