### ISSUE TITLE
Bold italics are not supported

### ISSUE THREAD

**Issue by zh-pan** [pbek/qmarkdowntextedit#177]
If I write ***Bold&italics***, the result is incorrect.
```
***Bold&italics***
```

**Comment by zh-pan** [comment]
![image](https://user-images.githubusercontent.com/45628282/204102081-83a451b6-b158-4b44-bcc3-872959cbd51e.png)

**Comment by pbek** [comment]
I don't think we were supporting mixing styles, did we, @Waqar144?

**Comment by Waqar144** [comment]
It is supported, try with a different font.

I doubt its broken as the relevant code hasn't been touched in at least a year

**Comment by zh-pan** [comment]
Thanks reply.
I try debug code, and find something with: 
https://github.com/pbek/qmarkdowntextedit/blob/17ea661f4a87e95a16cdda9e1590cc0d476a76cd/markdownhighlighter.cpp#L2300
Code above only bold and italic logical branches, lack mixing styles.
So can you help me how to fix this?

**Comment by zh-pan** [comment]
I try fix this. And only make little change for supporting mixing styles. The result like this:
<img width="98" alt="image" src="https://user-images.githubusercontent.com/45628282/204124915-d36332a9-e999-49c2-9ba9-05536dd9a1a4.png">

But I don't know this change Whether it will bring side effects, because I didn't spend much time looking at the rest of the code.

Can I make a pr?

**Comment by Waqar144** [comment]
It is broken since https://github.com/pbek/qmarkdowntextedit/commit/5d990c5416cd3b30020fbc7f633280002a37a82a.

**Comment by Waqar144** [comment]
other broken stuff

![image](https://user-images.githubusercontent.com/7696024/204126146-280a4be8-9a3c-410b-a57e-35c7093492e5.png)

**Comment by zh-pan** [comment]
Yes, `setFont` will override `Bold` or `Italic`. So I add a new font `BoldItalic`.  like this:

<img width="595" alt="image" src="https://user-images.githubusercontent.com/45628282/204126928-ca449c66-813c-4b9b-be63-0989ecacb83d.png">

And `BoldItalic`:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/45628282/204126971-c1db28ab-fd15-4019-821a-e5eff68d1d27.png">

---

> It is broken since [5d990c5](https://github.com/pbek/qmarkdowntextedit/commit/5d990c5416cd3b30020fbc7f633280002a37a82a).

> Or delete the two `fmt.setFont` can work, too?

**Comment by Waqar144** [comment]
Font needs to be overwritten only if it was set / different. Just setting the font always is incorrect. You can test with QOwnNotes whether your change works for both cases i.e., when a font is set or not. (Read the linked QOwnNotes issue)

Adding `BoldItalic` is not needed.

**Comment by Waqar144** [comment]
@pbek mind creating prs for changes you do, especially for the code that I wrote? Please don't do direct master pushes because you have direct access.

**Comment by pbek** [comment]
@Waqar144, thank you.
Yes, best investigate in QOwnNotes, if you are using that, @zh-pan.
Those styles were never planned to work in conjunction in QOwnNotes.

**Comment by pbek** [comment]
And please open an issue in QOwnNotes.

**Comment by pbek** [comment]
I'll add that with https://github.com/pbek/QOwnNotes/issues/2676.

**Comment by Waqar144** [comment]
This is a qmarkdowntextedit bug, it can't be fixed in QOwnNotes

**Comment by pbek** [comment]
Ah, I had to little sleep.

**Comment by pbek** [comment]
I didn't even saw it was in `markdownhighlighter.cpp` directly...

![image](https://user-images.githubusercontent.com/1798101/204486294-7ea37844-1403-4f59-8c7f-7eef8d1f114b.png)

**Comment by zh-pan** [comment]
Yes. You can remove this commit's change(https://github.com/pbek/qmarkdowntextedit/commit/5d990c5416cd3b30020fbc7f633280002a37a82a ).

Or make a new format with mixing styles.

**Comment by Waqar144** [comment]
I think to fix it, one needs to check if the font is something different and then change? like the other checks below. Not sure though

**Comment by pbek** [comment]
I already fixed it (see screenshot), it's not committed yet.

**Comment by pbek** [comment]
Should be fixed now.

**Comment by zh-pan** [comment]
That's great!

**Comment by zh-pan** [comment]
Windows will be crash when I use this commit. When input the fifth character '*'.
`***1*`: Note: The last '\*' key down will crash.

I want know this isn't my problem?

![image](https://user-images.githubusercontent.com/45628282/204803484-9edda7fa-de36-4dd9-8609-4890cb64d184.png)

**Comment by zh-pan** [comment]
I'm sure this commit caused the error. It also appears when I compile with the original project.

**Comment by zh-pan** [comment]
> I'm sure this commit caused the error. It also appears when I compile with the original project.

- windows 10 LTSC
- vs2022
- Qt6.4

Qt creator will crash, too.

**Comment by pbek** [comment]
>  It also appears when I compile with the original project.

What original project?

> Qt creator will crash, too.

Qt creator crashes!?

**Comment by pbek** [comment]
The commit just uses https://doc.qt.io/qt-5/qtextcharformat.html#setFontFamily...

**Comment by zh-pan** [comment]
I found problems with using qmarkdowntextedit as a 3rd party library in VS2022, then I tried to build QMarkDowntextedit-exe using the qmarkdowntextedit project and also got an error. I also tested compiling qmarkdowntextedit-exe in Qt creator with the same error. mingw and msvc2019 were used, respectively.

**Comment by zh-pan** [comment]
![image](https://user-images.githubusercontent.com/45628282/204952126-41374ad1-e1be-4b47-a78b-9e286875f95e.png)

**Comment by zh-pan** [comment]
![image](https://user-images.githubusercontent.com/45628282/204957949-fa4c0c66-417f-41c0-bc6b-a0feb56f0339.png)

**Comment by pbek** [comment]
Hmmm... I don't have any issues under Windows with Qt 5.11.

**Comment by pbek** [comment]
What's the content of `_formats[Bold].fontFamilies()` for you if you output it e.g. with `qDebug()`?

**Comment by Waqar144** [comment]
He is using Qt 6.4, it will easily crash there

**Comment by pbek** [comment]
I need to wait until I'll hit a box where I've Qt6 running then...

**Comment by Waqar144** [comment]
Then best not bump it in QON till its properly fixed.

**Comment by pbek** [comment]
There is no issue with the Qt5 builds as far as I'm aware of.

**Comment by Waqar144** [comment]
if there is no qt6 end user build, then it would be fine. But its trivial to fix either ways.

**Comment by pbek** [comment]
Feel free to make a PR if you have faster access than me to a Qt6 box then. 😉

**Comment by Waqar144** [comment]
Open up master, i will push a fix ;)

**Comment by pbek** [comment]
Should be fixed now.
