### ISSUE TITLE
Bringing features from QTextMarkdownWriter

### ISSUE THREAD

**Issue by nuttyartist** [pbek/qmarkdowntextedit#181]
Hey,

I've been using the QTextEdit example that comes with Qt and saw that it supports lists withe nice rendering and handling of checkboxes and other items.

![test](https://user-images.githubusercontent.com/16375940/230116116-201e1c3f-474d-471b-bebd-884b81712e36.gif)

Do you think we can bring it into QMarkdownTextEdit?

Here's the example:

https://doc.qt.io/qt-6/qtwidgets-richtext-textedit-example.html

**Comment by pbek** [comment]
QTextEdit is a Rich Text Editor that uses HTML as "base". QMarkdownTextEdit doesn't do HTML, it does Plain Text (with QPlainTextEdit as basis).

> Do you think we can bring it into QMarkdownTextEdit?

...so the simple answer is: no 😁

**Comment by pbek** [comment]
But what was it you are trying to achieve?

**Comment by nuttyartist** [comment]
> But what was it you are trying to achieve?

Well, I mainly want to add rendered checkboxes and bullet lists.

But I also wish to support adding more active, custom widgets into QTextEdit (although that is less of a priority). See: https://github.com/nuttyartist/notes/issues/560

**Comment by pbek** [comment]
Hehe, please keep me posted about your progress. 😁

**Comment by nuttyartist** [comment]
Hey there. While I didn't end up adding custom widgets to QTextEdit, I built my own block editor with the model in C++ and the view in QML. The underlying data structure is just plaintext.  Here's the progress so far (neat the end I show QTextMarkdown with the same underlying plaintext):

https://github.com/pbek/qmarkdowntextedit/assets/16375940/d5406f1f-3cec-453c-a9a9-d401273ac7b3

**Comment by nuttyartist** [comment]
> Is there also a view where it shows the plain-text? 

Yes, I just implemented one at this very moment. I'm using QMarkdownTextEdit with the QML exposed by @tim-gromeyer.

**Comment by tim-gromeyer** [comment]
> Hey there. While I didn't end up adding custom widgets to QTextEdit, I built my own block editor with the model in C++ and the view in QML. The underlying data structure is just plaintext.  Here's the progress so far (near the end I show QTextMarkdown with the same underlying plaintext):
> 
> https://github.com/pbek/qmarkdowntextedit/assets/16375940/d5406f1f-3cec-453c-a9a9-d401273ac7b3

This looks really neat!!
