### ISSUE TITLE
Support for Forth Syntax Highlighting

### ISSUE THREAD

**Issue by 0x3508A** [pbek/qmarkdowntextedit#182]
Thanks for creating this very wonderful effective control for Qt.
I am an avid user of the QOwnNotes and a Forth enthusiast.

While adding Forth code, I found that there is no highlighting support.
I wish to request your kind help regarding the same.

In line with this, I have taken a fork and placed in my changes.
Initially, the `gforth` words are added as the keywords.
There is also addition of special filter functions to help with comment highlighting.

This would be the first time I am trying to contribute to a project.
Please guide me and help me correct my mistakes.

**Comment by pbek** [comment]
Looking forward to it 😁

**Comment by 0x3508A** [comment]
Thanks again for guiding this through.
I have added an issue on the QOwnNotes as well https://github.com/pbek/QOwnNotes/issues/2780
With this issue, I have now learned how to properly commit code that would help the developers to audit and accept features.

Kindly guide me to add the the finally support for Forth Programming language highlighting in QOwnNotes.

**Comment by pbek** [comment]
Awesome, thank you! I'll close this then.
