### ISSUE TITLE
Idea: Highlight links in headings

### ISSUE THREAD

**Issue by tim-gromeyer** [pbek/qmarkdowntextedit#195]
Would it be a good idea if I implemented highlighting in headings? 

My idea is to highlight them normally, like any link, but we don't highlight the title itself. Here is an example:

![image](https://github.com/pbek/qmarkdowntextedit/assets/58736434/b0731019-b625-4421-aa16-a31d25ed0a5c)

The yellow parts will be highlighted with masked syntax (like the #) and the other part will not be highlighted at all.

**Comment by pbek** [comment]
Looks good to me. Go for it! 😊👍🏻
