### ISSUE TITLE
Falsely highlighting of links in code blocks

### ISSUE THREAD

**Issue by pbek** [pbek/qmarkdowntextedit#199]
@tim-gromeyer, unfortunately https://github.com/pbek/qmarkdowntextedit/commit/53c4c598 of https://github.com/pbek/qmarkdowntextedit/pull/188 did break something else too:

```markdown

    wget http://google.com

```

`http://google.com` is now highlighted as link, but it shouldn't.

_Originally posted by @pbek in https://github.com/pbek/qmarkdowntextedit/issues/188#issuecomment-1839158353_

**Comment by pbek** [comment]
I haven't seen links being highlighted in 4-Spaces fence code blocks so far... GitHub also doesn't highlight them, for example. And qmarkdowntextedit also doesn't highlight them in backtick code blocks...

**Comment by tim-gromeyer** [comment]
Okay, I'll look into that tomorrow.

Can you give me some more examples where it highlights when it shouldn't and vice versa?

**Comment by pbek** [comment]
That was the only thing that was reported so far.
