### ISSUE TITLE
Options for a WYSIWYG editor?

### ISSUE THREAD

**Issue by ThomasDaheim** [pbek/qmarkdowntextedit#2]
Hi,

since https://github.com/Fmstrat/ownnote isn't really maintained anymore I'm looking for a new notes editor for nextcloud. Unfortunately, I'm a big fan of WYSIWYG editors - thats whats stopping me to switch to e.g. notes for nextcloud.

I could live with a "normal" md editor in the web (since I'm only editing offline anyways) but under Win I would really love to use a WYSIWYG editor. Had a look at your code but my c++ is a bit rusty :-) So before digging deeper: Do you see any chance to be able to replace the current editor with another one? (not even sure if there currently is such a thing as a WYSIWYG editor in c++...).

Thanks,
Thomas

**Comment by pbek** [comment]
There is <http://doc.qt.io/qt-5/qtextedit.html>, but it outputs HTML and QOwnNotes will not use HTML (also see: <http://www.qownnotes.org/Knowledge-base/Does-QOwnNotes-support-ownNote>), so currently it doesn't look like there will be a WYSIWYG editor.

**Comment by ThomasDaheim** [comment]
I would have no issue in trying to add an on-the-fly mapper from md <-> html :-)

**Comment by pbek** [comment]
Wouldn't that defy the reason for QMarkdownTextEdit?
QMarkdownTextEdit is a C++ Qt QTextEdit widget with markdown highlighting and some other goodies. :smile: 

Or are you talking about <https://github.com/pbek/QOwnNotes>?

**Comment by ThomasDaheim** [comment]
Uups, that might explain things - https://github.com/pbek/QOwnNotes is where this issue should have ended up... Not sure how I got here.

Is there any way tp move the discussion to there?  Or should I open the issue once again in the right place?

Sorry!

**Comment by pbek** [comment]
I don't know a way to move issues on GitHub.
You can open the issue at the QOwnNotes repository, but there already were some requests about WYSIWYG: <https://github.com/pbek/QOwnNotes/issues?utf8=%E2%9C%93&q=wysiwyg>

Feel free to play around with the source code, I'm curious what you will invent.

**Comment by ThomasDaheim** [comment]
Thanks, will see if I can come up with some clever ideas :-)
