### ISSUE TITLE
License of markdownhighlighter

### ISSUE THREAD

**Issue by badaix** [pbek/qmarkdowntextedit#22]
Hi @pbek,

I would like to use the markdownhighlighter class in a project and I saw that in the file headers the license is set to GPLv2, while the project is under MIT license. 
Can you please clarify which one is the valid license?

thanks a lot in advance,
Johannes

**Comment by pbek** [comment]
I made it MIT back then, if you see some other headers you may change them to MIT and submit a pull request. 😄
