### ISSUE TITLE
README and screenshots are outdated

### ISSUE THREAD

**Issue by Waqar144** [pbek/qmarkdowntextedit#44]

**Comment by pbek** [comment]
Do you want to update them? :grin:

**Comment by Waqar144** [comment]
> Do you want to update them? grin

I use darkmode, screenshots look terrible in that :rofl:

**Comment by pbek** [comment]
Looking great. :grin:

**Comment by Waqar144** [comment]
> Looking great. grin

Thanks. I disabled the background for `Code Blocks` because in dark mode, text becomes unreadable. We still need it for `inline code` though, a color that fits nicely in both dark and light mode
